# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer.proto',
  package='customer',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63ustomer.proto\x12\x08\x63ustomer\"\xdf\x01\n\x0f\x43ustomerRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x34\n\taddresses\x18\x05 \x03(\x0b\x32!.customer.CustomerRequest.Address\x1a^\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x19\n\x11isShippingAddress\x18\x05 \x01(\x08\"/\n\x10\x43ustomerResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"!\n\x0e\x43ustomerFilter\x12\x0f\n\x07keyword\x18\x01 \x01(\t2\x9e\x01\n\x08\x43ustomer\x12G\n\x0cGetCustomers\x12\x18.customer.CustomerFilter\x1a\x19.customer.CustomerRequest\"\x00\x30\x01\x12I\n\x0e\x43reateCustomer\x12\x19.customer.CustomerRequest\x1a\x1a.customer.CustomerResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CUSTOMERREQUEST_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='customer.CustomerRequest.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='street', full_name='customer.CustomerRequest.Address.street', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='customer.CustomerRequest.Address.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='customer.CustomerRequest.Address.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zip', full_name='customer.CustomerRequest.Address.zip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isShippingAddress', full_name='customer.CustomerRequest.Address.isShippingAddress', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=252,
)

_CUSTOMERREQUEST = _descriptor.Descriptor(
  name='CustomerRequest',
  full_name='customer.CustomerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='customer.CustomerRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='customer.CustomerRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='customer.CustomerRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='customer.CustomerRequest.phone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='customer.CustomerRequest.addresses', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMERREQUEST_ADDRESS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=252,
)


_CUSTOMERRESPONSE = _descriptor.Descriptor(
  name='CustomerResponse',
  full_name='customer.CustomerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='customer.CustomerResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='customer.CustomerResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=301,
)


_CUSTOMERFILTER = _descriptor.Descriptor(
  name='CustomerFilter',
  full_name='customer.CustomerFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword', full_name='customer.CustomerFilter.keyword', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=336,
)

_CUSTOMERREQUEST_ADDRESS.containing_type = _CUSTOMERREQUEST
_CUSTOMERREQUEST.fields_by_name['addresses'].message_type = _CUSTOMERREQUEST_ADDRESS
DESCRIPTOR.message_types_by_name['CustomerRequest'] = _CUSTOMERREQUEST
DESCRIPTOR.message_types_by_name['CustomerResponse'] = _CUSTOMERRESPONSE
DESCRIPTOR.message_types_by_name['CustomerFilter'] = _CUSTOMERFILTER

CustomerRequest = _reflection.GeneratedProtocolMessageType('CustomerRequest', (_message.Message,), dict(

  Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
    DESCRIPTOR = _CUSTOMERREQUEST_ADDRESS,
    __module__ = 'customer_pb2'
    # @@protoc_insertion_point(class_scope:customer.CustomerRequest.Address)
    ))
  ,
  DESCRIPTOR = _CUSTOMERREQUEST,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerRequest)
  ))
_sym_db.RegisterMessage(CustomerRequest)
_sym_db.RegisterMessage(CustomerRequest.Address)

CustomerResponse = _reflection.GeneratedProtocolMessageType('CustomerResponse', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERRESPONSE,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerResponse)
  ))
_sym_db.RegisterMessage(CustomerResponse)

CustomerFilter = _reflection.GeneratedProtocolMessageType('CustomerFilter', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERFILTER,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerFilter)
  ))
_sym_db.RegisterMessage(CustomerFilter)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class CustomerStub(object):
    """The Customer service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetCustomers = channel.unary_stream(
          '/customer.Customer/GetCustomers',
          request_serializer=CustomerFilter.SerializeToString,
          response_deserializer=CustomerRequest.FromString,
          )
      self.CreateCustomer = channel.unary_unary(
          '/customer.Customer/CreateCustomer',
          request_serializer=CustomerRequest.SerializeToString,
          response_deserializer=CustomerResponse.FromString,
          )


  class CustomerServicer(object):
    """The Customer service definition.
    """

    def GetCustomers(self, request, context):
      """Get all Customers with filter - A server-to-client streaming RPC.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def CreateCustomer(self, request, context):
      """Create a new Customer - A simple RPC 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_CustomerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetCustomers': grpc.unary_stream_rpc_method_handler(
            servicer.GetCustomers,
            request_deserializer=CustomerFilter.FromString,
            response_serializer=CustomerRequest.SerializeToString,
        ),
        'CreateCustomer': grpc.unary_unary_rpc_method_handler(
            servicer.CreateCustomer,
            request_deserializer=CustomerRequest.FromString,
            response_serializer=CustomerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'customer.Customer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaCustomerServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The Customer service definition.
    """
    def GetCustomers(self, request, context):
      """Get all Customers with filter - A server-to-client streaming RPC.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def CreateCustomer(self, request, context):
      """Create a new Customer - A simple RPC 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaCustomerStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The Customer service definition.
    """
    def GetCustomers(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Get all Customers with filter - A server-to-client streaming RPC.
      """
      raise NotImplementedError()
    def CreateCustomer(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Create a new Customer - A simple RPC 
      """
      raise NotImplementedError()
    CreateCustomer.future = None


  def beta_create_Customer_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('customer.Customer', 'CreateCustomer'): CustomerRequest.FromString,
      ('customer.Customer', 'GetCustomers'): CustomerFilter.FromString,
    }
    response_serializers = {
      ('customer.Customer', 'CreateCustomer'): CustomerResponse.SerializeToString,
      ('customer.Customer', 'GetCustomers'): CustomerRequest.SerializeToString,
    }
    method_implementations = {
      ('customer.Customer', 'CreateCustomer'): face_utilities.unary_unary_inline(servicer.CreateCustomer),
      ('customer.Customer', 'GetCustomers'): face_utilities.unary_stream_inline(servicer.GetCustomers),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Customer_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('customer.Customer', 'CreateCustomer'): CustomerRequest.SerializeToString,
      ('customer.Customer', 'GetCustomers'): CustomerFilter.SerializeToString,
    }
    response_deserializers = {
      ('customer.Customer', 'CreateCustomer'): CustomerResponse.FromString,
      ('customer.Customer', 'GetCustomers'): CustomerRequest.FromString,
    }
    cardinalities = {
      'CreateCustomer': cardinality.Cardinality.UNARY_UNARY,
      'GetCustomers': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'customer.Customer', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
